[Desktop Entry]
Encoding=UTF-8
Comment=Custom account configuration user interface for accounts using the Pintxo connection manager.
Comment[cs]=Vlastní uživatelské rozhraní nastavení účtů pro účty používající správce spojení Pintxo.
Comment[es]=Interfaz de configuración de cuentas personalizadas para las cuentas que usen el gestor de conexiones Pintxo.
Comment[fi]=Pintxo-yhteyshallintaa käyttävien tilien mukautettu hallintakäyttöliittymä.
Comment[it]=Interfaccia utente personalizzata di configurazione account per account che usano il gestore di connessioni Pintxo.
Comment[nl]=Gebruikersinterface voor aangepaste accountconfiguratie voor accounts die de Pintxo verbindingenbeheerder gebruiken.
Comment[pt]=Interface de utilizador de configuração de contas personalizadas com o gestor de ligações Pintxo.
Comment[pt_BR]=Interface de configuração de contas personalizadas usando o gerenciador de conexões Pintxo.
Comment[sl]=Uporabniški vmesnik za prilagoditev računov, ki uporabljajo upravljalnik povezav Pintxo.
Comment[sv]=Användargränssnitt för anpassad kontoinställning av konton som använder anslutningshanteraren Pintxo.
Comment[uk]=Інтерфейс користувача для нетипового налаштовування облікових записів, для роботи яких використовуються засоби керування з’єднанням Pintxo.
Comment[x-test]=xxCustom account configuration user interface for accounts using the Pintxo connection manager.xx
Icon=phone
Name=Pintxo Account Configuration User Interface
Name[cs]=Uživatelské rozhraní nastavení účtu Pintxo
Name[es]=Interfaz de configuración de cuentas Pintxo
Name[fi]=Pintxo-tilinmäärityksen käyttöliittymä
Name[it]=Interfaccia utente di configurazione account Pintxo
Name[nl]=Gebruikersinterface voor Pintxo accountconfiguratie
Name[pt]=Interface de Configuração de Contas do Pintxo
Name[pt_BR]=Interface de configuração de contas do Pintxo
Name[sl]=Uporabniški vmesnik za nastavitev računov Pintxo
Name[sv]=Användargränssnitt för inställning av Pintxo-konton
Name[uk]=Інтерфейс користувача для налаштовування облікового запису Pintxo
Name[x-test]=xxPintxo Account Configuration User Interfacexx
Type=Service
ServiceTypes=KTpAccountsKCM/AccountUiPlugin

X-KDE-Library=ktpaccountskcm_plugin_pintxo
X-KDE-PluginInfo-Author=Anant Kamath
X-KDE-PluginInfo-Email=kamathanant@gmail.com
X-KDE-PluginInfo-Name=pintxo
X-KDE-PluginInfo-Version=@KTP_ACCOUNTS_KCM_VERSION@
X-KDE-PluginInfo-Website=http://techbase.kde.org/Projects/Telepathy
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
