[Desktop Entry]
Encoding=UTF-8
Comment=Custom account configuration user interface for accounts using the Pintxo connection manager.
Comment[bs]=Korisnički interfejs za konfiguraciju korisničkih naloga koristeći Pinxto menadžer konekcja.
Comment[ca]=Interfície d'usuari de configuració de compte personalitzat per comptes que utilitzen el gestor de connexions Pintxo.
Comment[cs]=Vlastní uživatelské rozhraní nastavení účtů pro účty používající správce spojení Pintxo.
Comment[de]=Eigene Benutzeroberfläche zum Einrichten von Zugängen, die die Pintxo-Verbindungsverwaltung verwenden.
Comment[fr]=Interface utilisateur de configuration de comptes pour les comptes employant le gestionnaire de connexion « Pintxo ».
Comment[it]=Interfaccia utente personalizzata di configurazione account per account che usano il gestore di connessioni Pintxo.
Comment[kk]=Pintxo байланыс менеджерін қолданатын тіркелгі пайдаланушы интерфейс параметрлерін ыңғайлау.
Comment[nl]=Gebruikersinterface voor aangepaste accountconfiguratie voor accounts die de Pintxo verbindingenbeheerder gebruiken.
Comment[pt_BR]=Interface de configuração de contas personalizadas usando o gerenciador de conexões Pintxo.
Comment[sk]=Vlastné používateľské rozhranie konfigurácie účtu pre účty používajúce správcu pripojení Pintxo.
Comment[sv]=Användargränssnitt för anpassad kontoinställning av konton som använder anslutningshanteraren Pintxo.
Comment[uk]=Інтерфейс користувача для нетипового налаштовування облікових записів, для роботи яких використовуються засоби керування з’єднанням Pintxo.
Comment[x-test]=xxCustom account configuration user interface for accounts using the Pintxo connection manager.xx
Icon=phone
Name=Pintxo Account Configuration User Interface
Name[bs]=Korisnički interfejs za konfiguraciju korisničkih naloga Pinxto
Name[ca]=Interfície d'usuari de configuració de compte de Pintxo
Name[cs]=Uživatelské rozhraní nastavení účtu Pintxo
Name[de]=Benutzeroberfläche zur Einrichtung von Pintxo-Zugängen
Name[fr]=Interface utilisateur pour la configuration de comptes « Pintxo ».
Name[it]=Interfaccia utente di configurazione account Pintxo
Name[kk]=Pintxo тіркелгі пайдаланушы интерфейсін баптау
Name[nl]=Gebruikersinterface voor Pintxo accountconfiguratie
Name[pt_BR]=Interface de configuração de contas do Pintxo
Name[sk]=Používateľské rozhranie konfigurácie účtu Pintxo
Name[sv]=Användargränssnitt för inställning av Pintxo-konton
Name[uk]=Інтерфейс користувача для налаштовування облікового запису Pintxo
Name[x-test]=xxPintxo Account Configuration User Interfacexx
Type=Service
ServiceTypes=KTpAccountsKCM/AccountUiPlugin

X-KDE-Library=ktpaccountskcm_plugin_pintxo
X-KDE-PluginInfo-Author=Anant Kamath
X-KDE-PluginInfo-Email=kamathanant@gmail.com
X-KDE-PluginInfo-Name=pintxo
X-KDE-PluginInfo-Version=@KTP_ACCOUNTS_KCM_VERSION@
X-KDE-PluginInfo-Website=http://techbase.kde.org/Projects/Telepathy
X-KDE-PluginInfo-License=GPL
X-KDE-PluginInfo-EnabledByDefault=true
