[Desktop Entry]
Encoding=UTF-8
Comment=Custom account configuration user interface for accounts using the sipe connection manager.
Comment[bs]=Korisnički interfejs za konfiguraciju korisničkih naloga koristeći sipzmenadžer konekcja.
Comment[ca]=Interfície d'usuari de configuració de compte personalitzat per comptes que utilitzen el gestor de connexions Sipe.
Comment[cs]=Vlastní uživatelské rozhraní nastavení účtů pro účty používající správce spojení sipe.
Comment[de]=Eigene Benutzeroberfläche zum Einrichten von Zugängen, die die Sipe-Verbindungsverwaltung verwenden.
Comment[fi]=Sipe-yhteyshallintaa käyttävien tilien mukautettu hallintakäyttöliittymä.
Comment[fr]=Interface utilisateur personnalisée pour la configuration de comptes en utilisant le gestionnaire de connexions « sipe ».
Comment[ia]=Interfacie de usator pro configuration de conto personalisate pro contos usante le gerente de connexion sipe.
Comment[lt]=Savito paskyros konfigūravimo naudotojo sąsaja paskyroms naudojant sipe ryšio tvarkyklę.
Comment[nb]=Brukerflate for å sette opp egendefinerte kontoer ved bruk av sipe tilkoblingsbehandler.
Comment[nl]=Gebruikersinterface voor aangepaste accountconfiguratie voor accounts die de Sipe verbindingenbeheerder gebruiken.
Comment[pl]=Własny interfejsu użytkownika konfiguracji kont dla kont wykorzystujących menadżera połączeń sipe.
Comment[pt]=Interface de utilizador de configuração de contas personalizadas com o gestor de ligações Sipe.
Comment[pt_BR]=Interface de configuração de contas personalizadas usando o gerenciador de conexões Sipe.
Comment[sk]=Vlastné používateľské rozhranie konfigurácie účtu pre účty používajúce správcu pripojení Sipe.
Comment[sv]=Användargränssnitt för anpassad kontoinställning av konton som använder anslutningshanteraren Sipe.
Comment[uk]=Інтерфейс користувача для нетипового налаштовування облікового запису за допомогою керування з’єднаннями sipe.
Comment[x-test]=xxCustom account configuration user interface for accounts using the sipe connection manager.xx
Icon=blockdevice
Name=Sipe Account Configuration User Interface
Name[bs]=Korisnički interfejs za konfiguraciju korisničkih naloga Sipe
Name[ca]=Interfície d'usuari de configuració de compte de Sipe
Name[cs]=Uživatelské rozhraní nastavení účtu Sipe
Name[de]=Benutzeroberfläche zur Einrichtung von Sipe-Zugängen
Name[fi]=Sipe-tilinmäärityksen käyttöliittymä
Name[fr]=Interface utilisateur pour la configuration de comptes « sipe ».
Name[ia]=Interfacie de usator de configuration de conto de Sipe
Name[lt]=Sipe paskyros konfigūravimo naudotojo sąsaja
Name[nb]=Brukerflate for å sette opp Sipe-konto
Name[nl]=Gebruikersinterface voor Sipe accountconfiguratie
Name[pl]=Interfejs użytkownika konfiguracji konta Sipe
Name[pt]=Interface de Configuração de Contas do Sipe
Name[pt_BR]=Interface de configuração de contas do Sipe
Name[sk]=Používateľské rozhranie konfigurácie účtu Sipe
Name[sv]=Användargränssnitt för inställning av Sipe-konton
Name[uk]=Інтерфейс користувача для налаштовування sipe
Name[x-test]=xxSipe Account Configuration User Interfacexx
Type=Service
ServiceTypes=KTpAccountsKCM/AccountUiPlugin

X-KDE-Library=ktpaccountskcm_plugin_sipe
X-KDE-PluginInfo-Author=Maksim Melnikau
X-KDE-PluginInfo-Email=maxposedon@gmail.com
X-KDE-PluginInfo-Name=sipe
X-KDE-PluginInfo-Version=@KTP_ACCOUNTS_KCM_VERSION@
X-KDE-PluginInfo-Website=http://techbase.kde.org/Projects/Telepathy
X-KDE-PluginInfo-License=LGPL
X-KDE-PluginInfo-EnabledByDefault=true
